name: build aarch64
on: [push]
jobs:
  msys2-clangarm64:
    runs-on: windows-11-arm
    steps:
      - name: configure git line endings
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANGARM64
          update: true
          install: mingw-w64-clang-aarch64-gcc make diffutils sed mingw-w64-i686-gcc mingw-w64-x86_64-gcc
      - name: build heob
        shell: msys2 {0}
        run: |
          make BITS=64a PREF= WARN= FFREESTANDING= strip-heob64a
          make BITS=64a PREF= WARN= NO_THREAD_JUMPS= WARN_TEST=-Wno-implicit-exception-spec-mismatch allocer64a.exe
      - name: build heob32
        run: |
          set MSYSTEM=MINGW32
          msys2 -c 'make BITS=32 PREF= WARN= FFREESTANDING= strip-heob32'
      - name: build heob64
        run: |
          set MSYSTEM=MINGW64
          msys2 -c 'make BITS=64 PREF= WARN= FFREESTANDING= strip-heob64'
      - name: build dwarfstack
        shell: msys2 {0}
        run: |
          make -C dwarfstack bin/dwarfstack.dll
          cp -p dwarfstack/bin/dwarfstack.dll dwarfstack64.dll
      - name: upload executables
        uses: actions/upload-artifact@v4
        with:
          name: heob-aarch64
          if-no-files-found: error
          path: |
            heob64a.exe
            dwarfstack64.dll
            heob32.exe
            heob64.exe
      - name: jump thunk test
        shell: cmd
        run: |
          heob64a -"thunks-aarch64.dll"0x180000000 0x18000100b 0x18000100c 0x180001018 0x180001024 0x180001030 0x180001087 0x180001088 0x1800028af 0x1800028b0 0x1800040d7 0x1800040d8 0x1800058ff 0x180005900
      - name: WOW test
        shell: cmd
        run: |
          wow32.exe wow32.exe
          wow32.exe wow64.exe
          wow32.exe wow64a.exe
          heob32.exe wow32.exe
          heob32.exe wow64.exe
          heob32.exe wow64a.exe
          heob64.exe wow32.exe
          heob64.exe wow64.exe
          heob64.exe wow64a.exe
          heob64a.exe wow32.exe
          heob64a.exe wow64.exe
          heob64a.exe wow64a.exe
      - name: test
        shell: msys2 {0}
        run: |
          ./heob64a -p0 -n0 allocer64a 65 || true
          ./heob64a -Y2 allocer64a.exe || true
          ./heob64a -Y2 dll-alloc64a.dll || true
          ./heob64a -D15 ./allocer64a 2 || true
          ./heob64a -D-1 ./allocer64a 2 || true
          ./heob64a -D15 *.dmp
          ./heob64a -I10 -vprof.svg ./allocer64a 47 57 || true
          make BITS=64a PREF= test
          head -n-0 test*.diff
      - name: upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          if-no-files-found: error
          path: |
            allocer64a.exe
            dll-alloc64a.dll
            test*.diff
            crash*.dmp
            prof.svg
