name: build

on:
  push:
    branches:
      - ffmpeg-test-2

jobs:
  msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v6
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          pacboy: ffmpeg

      - name: breakpoint
        uses: fawazahmed0/action-debug-vscode@main

      - name: Test ffmpeg output
        run: |
          ./test.sh
