name: build aarch64
on: [push]
jobs:
  msys2-clangarm64:
    runs-on: windows-11-arm
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: msys2/setup-msys2@v2
        with:
          msystem: CLANGARM64
          update: true
          install: mingw-w64-clang-aarch64-gcc make diff
      - name: CI-Build
        shell: msys2 {0}
        run: |
          make BITS=64 PREF= WARN= heob64.exe
          make BITS=64 PREF= WARN= NO_THREAD_JUMPS= WARN_TEST=-Wno-implicit-exception-spec-mismatch allocer64.exe
          ./heob64 ./allocer64 1 || true
          ./heob64 ./allocer64 2 || true
          make BITS=64 PREF= test
