name: build with gcc
on: [push]
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: |
          gcc -v
          echo PATH=$env:PATH
      - run: |
          gcc -v
          make BITS=32 PREF= strip-heob32
        env:
          PATH: c:\mingw32\bin;${{ env.PATH }}
      - run: make BITS=64 PREF= strip-heob64
