name: build with gcc
on: [push]
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: gcc -v
      - run: make BITS=64 PREF= strip-heob64
      - run: gcc -v
        env:
          PATH: c:\mingw32\bin;${{ env.PATH }}
