name: build aarch64
on: [push]
jobs:
  msys2-clangarm64:
    runs-on: windows-11-arm
    steps:
      - name: configure git line endings
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANGARM64
          update: true
          install: mingw-w64-clang-aarch64-gcc make diffutils sed
      - name: build heob
        shell: msys2 {0}
        run: |
          make BITS=64 PREF= WARN= FFREESTANDING= strip-heob64
          make BITS=64 PREF= WARN= NO_THREAD_JUMPS= WARN_TEST=-Wno-implicit-exception-spec-mismatch allocer64.exe
      - name: build dwarfstack
        shell: msys2 {0}
        run: |
          make -C dwarfstack bin/dwarfstack.dll
          cp -p dwarfstack/bin/dwarfstack.dll dwarfstack64.dll
      - name: upload executables
        uses: actions/upload-artifact@v4
        with:
          name: heob-aarch64
          if-no-files-found: error
          path: |
            heob64.exe
            dwarfstack64.dll
      - name: test
        shell: msys2 {0}
        run: |
          ./heob64 -Y2 allocer64.exe || true
          ./heob64 -Y2 dll-alloc64.dll || true
          ./heob64 -D15 ./allocer64 2 || true
          ./heob64 -D-1 ./allocer64 2 || true
          ./heob64 -D15 *.dmp
          make BITS=64 PREF= test
          head -n-0 test*.diff
      - name: upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          if-no-files-found: error
          path: |
            allocer64.exe
            dll-alloc64.dll
            test*.diff
