name: build aarch64
on: [push]
jobs:
  msys2-clangarm64:
    runs-on: windows-11-arm
    steps:
      - name: configure git line endings
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANGARM64
          update: true
          install: mingw-w64-clang-aarch64-gcc make diffutils sed
      - name: build heob
        shell: msys2 {0}
        run: |
          make BITS=64 PREF= WARN= FFREESTANDING= strip-heob64
          make BITS=64 PREF= WARN= NO_THREAD_JUMPS= WARN_TEST=-Wno-implicit-exception-spec-mismatch allocer64.exe
      - name: build dwarfstack
        shell: msys2 {0}
        run: |
          make -C dwarfstack bin/dwarfstack.dll
          cp -p dwarfstack/bin/dwarfstack.dll dwarfstack64.dll
      - name: upload executables
        uses: actions/upload-artifact@v4
        with:
          name: heob-aarch64
          if-no-files-found: error
          path: |
            heob64.exe
            dwarfstack64.dll
      - name: jump thunk test
        shell: cmd
        run: |
          heob64 -"thunks-aarch64.dll"0x180000000 0x18000100b 0x18000100c 0x180001018 0x180001024 0x180001030 0x180001087 0x180001088 0x1800028af 0x1800028b0 0x1800040d7 0x1800040d8 0x1800058ff 0x180005900
      - name: WOW test
        shell: cmd
        run: |
          wow32 wow32
          wow32 wow64
          wow32 wow64a
          wow64 wow32
          wow64 wow64
          wow64 wow64a
          wow64a wow32
          wow64a wow64
          wow64a wow64a
      - name: test
        shell: msys2 {0}
        run: |
          ./heob64 -p0 -n0 allocer64 65 || true
          ./heob64 -Y2 allocer64.exe || true
          ./heob64 -Y2 dll-alloc64.dll || true
          ./heob64 -D15 ./allocer64 2 || true
          ./heob64 -D-1 ./allocer64 2 || true
          ./heob64 -D15 *.dmp
          ./heob64 -I10 -vprof.svg ./allocer64 47 57 || true
          make BITS=64 PREF= test
          head -n-0 test*.diff
      - name: upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          if-no-files-found: error
          path: |
            allocer64.exe
            dll-alloc64.dll
            test*.diff
            crash*.dmp
            prof.svg
