name: build

on:
  push:
    branches:
      - master

jobs:
  msys2:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - sys: "clang64"
            os: "windows-latest"
          - sys: "mingw32"
            os: "windows-latest"
          - sys: "mingw64"
            os: "windows-latest"
          - sys: "ucrt64"
            os: "windows-latest"
          - sys: "clangarm64"
            os: "windows-11-arm"
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v6
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          update: true
          pacboy: ffmpeg

      - name: Test ffmpeg output
        run: |
          ./test.sh
